### PR TITLE
Update request.mojo

### PR DESCRIPTION
**Pull request by BarutSRB**

### CODE REVIEW

**Comment by saviorand** [comment]
@BarutSRB looks good so far, I'm wondering if we should move the new traits somewhere else e.g. strings.mojo , since they're high level and don't necessarily have to do with HTTP requests. What do you think?

**Comment by BarutSRB** [comment]
You're absolutely right. These traits are indeed high level and broadly applicable, they can be reused across lightbug so yeah putting them in strings.mojo would be the best.

**Comment by saviorand** [comment]
@BarutSRB done, moved the traits. I was trying to run `magic run mojo lightbug.🔥` but getting this error, do you also get this error locally? This is on the `HTTPRequest` struct

lightbug_http/http/request.mojo:18:2: error: '@value' cannot synthesize members: 'headers' has non-copyable, non-movable type 'HeaderType'
@value
 ^

**Comment by saviorand** [comment]
Btw, removed the comments on the methods for now until we come up with a unified doc comment style. Thanks for them though! I'll try to bring them back later, after this PR is merged

**Comment by saviorand** [comment]
Just ran the pipeline, can you see if you can fix the compilation errors? Happy to merge once everything works

**Pull request closed without merging**
