### PR TITLE
Switching ._buffer usage to .as_bytes() to fix early String termination

### PR DESCRIPTION
**Pull request by thatstoasty**
Copied from the other PR for feature/string-builder.
String's `._buffer` attribute compared to String's `as_bytes()` method is as follows:

```py
String("OK")._buffer -> [79, 75, 0]
String("OK").as_bytes() -> [79, 75]
```

._buffer includes the null terminator byte, which makes sense as to why the response was being terminated at 
`HTTP/1.1 200 OK`! The String constructor was not reading anything past that first terminator.

After a global replace of ._buffer with .as_bytes() this encode function worked and the server returned a response to my browser.

I tested changes locally with the Welcome handler, and one that returns test in the body. Both returned the correct response to my browser. Trying to run the test suite, but I'm running into some issues with the different Structs that implement `Connection` not all implementing the `read` function with the same signature. `SysConnection` looks like the odd one out.

### CODE REVIEW

**Comment by saviorand** [comment]
Thanks for the pull request! Will aim to review and merge today

**Comment by saviorand** [comment]
@thatstoasty if I wonder if it's a setup issue but if I run the updated code from this PR locally and open `localhost:8080` in the browser I get a malloc error (below). Do you not get this one?
```
🔥🐝 Lightbug is listening on http://0.0.0.0:8080
Ready to accept connections...
mojo(26145,0x1e2319ec0) malloc: Incorrect checksum for freed object 0x129023e00: probably modified after being freed.
Corrupt value: 0x61456e716e473031
mojo(26145,0x1e2319ec0) malloc: *** set a breakpoint in malloc_error_break to debug
Please submit a bug report to https://github.com/modularml/mojo/issues and include the crash backtrace along with all the relevant source codes.
Stack dump:
0.      Program arguments: mojo lightbug.\360\237\224\245
[26147:9964500:20240320,192415.718470:WARNING crash_report_exception_handler.cc:257] UniversalExceptionRaise: (os/kern) failure (5)
zsh: trace trap  mojo lightbug.🔥
```

**Comment by thatstoasty** [comment]
@saviorand Ah the classic "it works on my machine" haha. I'm on an M2 Mac, so that's strange, it should be pretty similar. When I run it I don't get that error, I am able to load the welcome screen with the lightbug mascot. Are you running Mojo 24.1?

**Comment by saviorand** [comment]
@thatstoasty yup, I'm on 24.1.0. Very weird, will try more on different devices

**Comment by thatstoasty** [comment]
I'm going to close this PR and open up one that I forked with main with more narrow changes.

**Pull request closed without merging**
